### ISSUE TITLE
Reference to "endpoint" in bowerrc

### ISSUE THREAD

**Issue by brettz9** [indieisaconcept/slim-bower-server#3]
Hi,

In the current [`.bowerrc` documentation](http://bower.io/docs/config/), I don't see any reference to "endpoint" as a property as per your README.

It looks like it should now be the "registry" property. Should I just submit a PR for changing this in the README, or have there since been other changes to Bower which won't allow it to work with your server?

Thanks!

**Comment by cornernote** [comment]
i agree that `endpoint` does not work but `registry` works

**Comment by indieisaconcept** [comment]
@brettz9 thanks for spotting this. I've not used this for sometime so it's likely the readme is indeed out of data. I'll update. Thanks
